name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Actualiza a la versión que usa Node 16

    - name: Setup SSH agent for bastion
      uses: webfactory/ssh-agent@v0.6.0  # Actualiza a la versión que usa Node 16
      with:
        ssh-private-key: ${{ secrets.APP_KEY }}

    - name: Add private key for internal SSH
      run: |
        echo "${{ secrets.APP_KEY }}" > key.pem
        chmod 600 key.pem

    - name: SSH to Bastion and then to Private Instance 1
      run: |
        ssh -o StrictHostKeyChecking=no -A ubuntu@54.67.86.50 << 'EOF'
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@10.0.4.75 << 'INNER_EOF'
            cd /home/ubuntu/time-app
            git pull origin main
            pkill -f app.py
            nohup python3 app.py &
          INNER_EOF
        EOF

    - name: SSH to Bastion and then to Private Instance 2
      run: |
        ssh -o StrictHostKeyChecking=no -A ubuntu@54.67.86.50 << 'EOF'
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@10.0.3.141 << 'INNER_EOF'
            cd /home/ubuntu/time-app
            git pull origin main
            pkill -f app.py
            nohup python3 app.py &
          INNER_EOF
        EOF

    - name: Cleanup
      run: rm key.pem